a = input('Digite algo: ')
print('O tipo primitivo desse valor é', type(a))
print('Só tem espaços: ', a.isspace())
print('É um número?', a.isalnum())
print('É alfabético? ', a.isalpha())
print('É alfanumérico? ', a.isalnum())
print('Ele esta em maiúscula? ', a.isupper())
print('Ele esta em minúsculas? ', a.islower())